/* tests/mlkem_test.c - ML-KEM-768, against itself and against OpenSSL
 *
 * A KEM that only talks to itself passes every test you can write without a
 * second implementation. Transpose the matrix, swap the two index bytes of the
 * XOF, order a hash's inputs backwards: each of those gives something that
 * encapsulates and decapsulates perfectly and interoperates with nothing.
 *
 * So the checks here are in two halves. The first half is self-consistency,
 * which catches the ordinary bugs. The second is a fixture generated by
 * OpenSSL 3.5 - a key pair from a known seed, and a ciphertext under it - and
 * that is the half that can fail in the way that matters.
 * tools/gen_mlkem_fixture.py regenerates it; the fixture is checked in so this
 * suite does not need OpenSSL to run, and the generator is checked in beside
 * it so the fixture is not a magic file.
 *
 * Build (Linux):   sh build.sh --crypto-tests && ./build/mlkem_test
 * Build (Windows): build.bat --crypto-tests && build\mlkem_test.exe
 *
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) 2026 Stanislav Saveliev and CybouDB Contributors
 */
#include <stdio.h>
#include <string.h>
#include <stdint.h>

#define EK_BYTES 1184
#define DK_BYTES 2400
#define CT_BYTES 1088
#define SS_BYTES 32

void cyboudb_mlkem_keygen(uint8_t *ek, uint8_t *dk, const uint8_t *d,
                          const uint8_t *z);
void cyboudb_mlkem_encaps(uint8_t *ct, uint8_t *ss, const uint8_t *ek,
                          const uint8_t *m);
void cyboudb_mlkem_decaps(uint8_t *ss, const uint8_t *ct, const uint8_t *dk);

#include "mlkem_fixture.h"

static int checks, failures;

static void check(const char *what, int ok) {
    checks++;
    if (ok) printf("ok   %s\n", what);
    else { failures++; printf("FAIL %s\n", what); }
}

static uint8_t ek[EK_BYTES], dk[DK_BYTES], ct[CT_BYTES];
static uint8_t ss_a[SS_BYTES], ss_b[SS_BYTES];

int main(void) {
    uint8_t d[32], z[32], m[32];
    int i;

    printf("CybouDB ML-KEM-768 test\n\n");

    for (i = 0; i < 32; i++) d[i] = (uint8_t)(i * 3 + 1);
    for (i = 0; i < 32; i++) z[i] = (uint8_t)(i * 5 + 2);
    for (i = 0; i < 32; i++) m[i] = (uint8_t)(i * 7 + 3);

    /* --- self-consistency --------------------------------------------------- */
    cyboudb_mlkem_keygen(ek, dk, d, z);
    cyboudb_mlkem_encaps(ct, ss_a, ek, m);
    cyboudb_mlkem_decaps(ss_b, ct, dk);
    check("what was encapsulated is what is decapsulated",
          memcmp(ss_a, ss_b, SS_BYTES) == 0);

    {
        uint8_t zero[SS_BYTES];
        memset(zero, 0, sizeof zero);
        check("and it is not zero", memcmp(ss_a, zero, SS_BYTES) != 0);
    }

    {
        static uint8_t ek2[EK_BYTES], dk2[DK_BYTES];
        cyboudb_mlkem_keygen(ek2, dk2, d, z);
        check("key generation is a function of its seed",
              memcmp(ek, ek2, EK_BYTES) == 0 &&
              memcmp(dk, dk2, DK_BYTES) == 0);

        d[0] ^= 0x01;
        cyboudb_mlkem_keygen(ek2, dk2, d, z);
        check("and one bit of the seed gives a different key",
              memcmp(ek, ek2, EK_BYTES) != 0);
        d[0] ^= 0x01;
    }

    {
        static uint8_t ct2[CT_BYTES];
        uint8_t ss2[SS_BYTES];
        cyboudb_mlkem_encaps(ct2, ss2, ek, m);
        check("encapsulation is a function of its message",
              memcmp(ct, ct2, CT_BYTES) == 0 &&
              memcmp(ss_a, ss2, SS_BYTES) == 0);

        m[31] ^= 0x01;
        cyboudb_mlkem_encaps(ct2, ss2, ek, m);
        check("and a different message gives a different secret",
              memcmp(ss_a, ss2, SS_BYTES) != 0);
        m[31] ^= 0x01;
    }

    /* --- implicit rejection -------------------------------------------------
       A damaged ciphertext does not produce an error, a zero, or anything a
       caller could test for. It produces a different shared secret, stably,
       and the engine finds out when the key does not unwrap - which is
       docs/PQ_KEM.md, Decision 5, and the reason the engine may not branch on
       a KEM result. */
    {
        static uint8_t bad[CT_BYTES];
        uint8_t ss_bad[SS_BYTES], ss_bad2[SS_BYTES], zero[SS_BYTES];
        memset(zero, 0, sizeof zero);
        memcpy(bad, ct, CT_BYTES);
        bad[100] ^= 0x01;

        cyboudb_mlkem_decaps(ss_bad, bad, dk);
        check("a damaged ciphertext still yields a secret",
              memcmp(ss_bad, zero, SS_BYTES) != 0);
        check("and it is not the right one",
              memcmp(ss_bad, ss_a, SS_BYTES) != 0);

        cyboudb_mlkem_decaps(ss_bad2, bad, dk);
        check("and it is the same one every time - implicit rejection is a "
              "function, not an accident",
              memcmp(ss_bad, ss_bad2, SS_BYTES) == 0);

        {
            static uint8_t dk2[DK_BYTES], ek2[EK_BYTES];
            uint8_t other_z[32], ss_other[SS_BYTES];
            memcpy(other_z, z, 32);
            other_z[0] ^= 0x01;
            cyboudb_mlkem_keygen(ek2, dk2, d, other_z);
            cyboudb_mlkem_decaps(ss_other, bad, dk2);
            check("and it depends on z, which is what makes it per-key",
                  memcmp(ss_bad, ss_other, SS_BYTES) != 0);
        }

        /* The last byte of the ciphertext is inside the compressed v, where a
           flip changes one coefficient by a sixteenth of q - too little to
           change the message, and the re-encryption catches it anyway. */
        memcpy(bad, ct, CT_BYTES);
        bad[CT_BYTES - 1] ^= 0x80;
        cyboudb_mlkem_decaps(ss_bad, bad, dk);
        check("a flip in the last byte is rejected too",
              memcmp(ss_bad, ss_a, SS_BYTES) != 0);
    }

    {
        static uint8_t dk2[DK_BYTES], ek2[EK_BYTES];
        uint8_t ss2[SS_BYTES];
        uint8_t other_d[32];
        memcpy(other_d, d, 32);
        other_d[5] ^= 0x01;
        cyboudb_mlkem_keygen(ek2, dk2, other_d, z);
        cyboudb_mlkem_decaps(ss2, ct, dk2);
        check("another key's holder gets nothing from this ciphertext",
              memcmp(ss2, ss_a, SS_BYTES) != 0);
    }

    /* --- OpenSSL ------------------------------------------------------------
       The half that a self-consistent mistake cannot pass. */
    {
        static uint8_t ek_f[EK_BYTES], dk_f[DK_BYTES];
        uint8_t ss_f[SS_BYTES];

        cyboudb_mlkem_keygen(ek_f, dk_f, fixture_d, fixture_z);
        check("the same seed gives OpenSSL's encapsulation key, byte for byte",
              memcmp(ek_f, fixture_ek, EK_BYTES) == 0);
        check("and OpenSSL's decapsulation key",
              memcmp(dk_f, fixture_dk, DK_BYTES) == 0);

        cyboudb_mlkem_decaps(ss_f, fixture_ct, dk_f);
        check("their ciphertext gives us their shared secret",
              memcmp(ss_f, fixture_ss, SS_BYTES) == 0);

        /* The other direction - we encapsulate, they decapsulate - cannot
           be a constant here: OpenSSL's command line supplies its own
           randomness, so a checked-in ciphertext of ours would be our output
           played back to us. tools/check_mlkem_interop.py runs that direction
           live against OpenSSL, and what stands in for it here is that our
           encapsulation under their key round-trips through the
           decapsulation key they generated. */
        cyboudb_mlkem_encaps(ct, ss_a, fixture_ek, m);
        cyboudb_mlkem_decaps(ss_f, ct, fixture_dk);
        check("and our encapsulation under their key opens with their key",
              memcmp(ss_a, ss_f, SS_BYTES) == 0);
    }

    printf("\nML-KEM suite: %d checks, %d failed\n", checks, failures);
    return failures ? 1 : 0;
}
