; Copyright (c) 2026 Stanislav Saveliev and CybouDB Contributors
; SPDX-License-Identifier: Apache-2.0
; =============================================================================
;  crypto/mlkem_poly.asm - the arithmetic ML-KEM is built out of
; =============================================================================
;  FIPS 203, and docs/PQ_KEM.md for why ML-KEM at all.
;
;  A polynomial is 256 coefficients modulo q = 3329, held as int16 in the
;  caller's 512 bytes. Everything works in the Montgomery domain, where a
;  modular multiplication is two multiplies and a subtract - no division, and
;  no branch that depends on a coefficient. That last property is the point:
;  secret polynomials pass through every routine in this file, and the table in
;  docs/PQ_KEM.md says which parts of ML-KEM are secret, which is all of them
;  except the sampling of the public matrix.
;
;  The twiddle factors are generated by tools/gen_mlkem_tables.py from what
;  they are defined to be, not transcribed. One wrong entry out of 128 gives
;  code that still looks like an NTT and still returns a polynomial.
; =============================================================================

%include "cyboudb.inc"

BITS 64
default rel

global cyboudb_mlkem_ntt
global cyboudb_mlkem_invntt
global cyboudb_mlkem_basemul
global cyboudb_mlkem_poly_add
global cyboudb_mlkem_poly_sub
global cyboudb_mlkem_poly_reduce
global cyboudb_mlkem_poly_tomont
global cyboudb_mlkem_montgomery_reduce
global cyboudb_mlkem_barrett_reduce

section .rodata
%include "mlkem_zetas.inc"

; mont^2 / 128 mod q: the scaling the inverse transform finishes with.
%define MLKEM_INVNTT_F 1441
; round(2^26 / q), for Barrett reduction.
%define MLKEM_BARRETT_V 20159

section .text

; -----------------------------------------------------------------------------
;  MONT_REDUCE - eax in [-2^15 q, 2^15 q) becomes ax = eax * 2^-16 mod q.
;  Clobbers edx. Branch-free, and nothing it does depends on the value.
; -----------------------------------------------------------------------------
%macro MONT_REDUCE 0
    movsx   edx, ax
    imul    edx, MLKEM_QINV
    movsx   edx, dx
    imul    edx, MLKEM_Q
    sub     eax, edx
    sar     eax, 16
%endmacro

; -----------------------------------------------------------------------------
;  BARRETT_REDUCE - ax becomes its representative in (-q/2, q/2].
;  Clobbers edx. The division by q that docs/PQ_KEM.md forbids on secret data
;  is done the way that is allowed: by a constant, as a multiply and a shift.
; -----------------------------------------------------------------------------
%macro BARRETT_REDUCE 0
    movsx   eax, ax
    imul    edx, eax, MLKEM_BARRETT_V
    add     edx, 1 << 25
    sar     edx, 26
    imul    edx, MLKEM_Q
    sub     eax, edx
%endmacro

; -----------------------------------------------------------------------------
;  FQMUL <dst32>, <a32>, <b32 or mem> - montgomery_reduce(a * b).
;  Clobbers eax and edx; dst must not be either.
; -----------------------------------------------------------------------------
%macro FQMUL 3
    mov     eax, %2
    imul    eax, %3
    MONT_REDUCE
    movsx   %1, ax
%endmacro

; =============================================================================
;  cyboudb_mlkem_montgomery_reduce(a) -> int16
;  cyboudb_mlkem_barrett_reduce(a) -> int16
;
;  Exported so a test can drive them across their whole input range instead of
;  only through the polynomials that happen to reach them.
; =============================================================================
cyboudb_mlkem_montgomery_reduce:
    mov     eax, ARG1d
    MONT_REDUCE
    movsx   eax, ax
    ret

cyboudb_mlkem_barrett_reduce:
    mov     eax, ARG1d
    BARRETT_REDUCE
    movsx   eax, ax
    ret

; =============================================================================
;  cyboudb_mlkem_ntt(r)
;
;  Seven layers, halving the distance each time - FIPS 203 Algorithm 9. Every
;  loop bound here is public: they are the shape of the transform and say
;  nothing about the data passing through it.
; =============================================================================
cyboudb_mlkem_ntt:
    FRAME_BEGIN 64, 0
    mov     [rbp - 8], rbx
    mov     [rbp - 16], r12
    mov     [rbp - 24], r13
    mov     [rbp - 32], r14
    mov     [rbp - 40], r15

    mov     rbx, ARG1
    lea     r14, [mlkem_zetas]
    mov     r15, 1                      ; k
    mov     r12, 128                    ; len

.layer:
    xor     r13, r13                    ; start
.block:
    movsx   r10d, word [r14 + r15 * 2]  ; zeta
    inc     r15
    mov     r11, r13                    ; j
    mov     rcx, r13
    add     rcx, r12                    ; where this block ends
    mov     [rbp - 48], rcx

.butterfly:
    mov     rcx, r11
    add     rcx, r12
    movsx   eax, word [rbx + rcx * 2]
    imul    eax, r10d
    MONT_REDUCE
    movsx   r8d, ax                             ; t = zeta * r[j + len]

    movsx   r9d, word [rbx + r11 * 2]           ; r[j]
    mov     eax, r9d
    sub     eax, r8d
    mov     [rbx + rcx * 2], ax                 ; r[j + len] = r[j] - t
    add     r9d, r8d
    mov     [rbx + r11 * 2], r9w                ; r[j]     = r[j] + t

    inc     r11
    cmp     r11, [rbp - 48]
    jb      .butterfly

    lea     r13, [r13 + r12 * 2]
    cmp     r13, 256
    jb      .block

    shr     r12, 1
    cmp     r12, 2
    jae     .layer

    ; One Barrett pass at the end, so a caller gets coefficients in a known
    ; range rather than whatever seven layers of growth happened to leave.
    xor     rcx, rcx
.reduce:
    mov     ax, [rbx + rcx * 2]
    BARRETT_REDUCE
    mov     [rbx + rcx * 2], ax
    inc     rcx
    cmp     rcx, 256
    jb      .reduce

    mov     rbx, [rbp - 8]
    mov     r12, [rbp - 16]
    mov     r13, [rbp - 24]
    mov     r14, [rbp - 32]
    mov     r15, [rbp - 40]
    FRAME_END
    ret

; =============================================================================
;  cyboudb_mlkem_invntt(r)
;
;  The Gentleman-Sande half, walking the twiddles backwards, and the final
;  scaling by mont^2 / 128 that turns the sum back into a polynomial.
; =============================================================================
cyboudb_mlkem_invntt:
    FRAME_BEGIN 64, 0
    mov     [rbp - 8], rbx
    mov     [rbp - 16], r12
    mov     [rbp - 24], r13
    mov     [rbp - 32], r14
    mov     [rbp - 40], r15

    mov     rbx, ARG1
    lea     r14, [mlkem_zetas]
    mov     r15, 127                    ; k
    mov     r12, 2                      ; len

.layer:
    xor     r13, r13
.block:
    movsx   r10d, word [r14 + r15 * 2]
    dec     r15
    mov     r11, r13
    mov     rcx, r13
    add     rcx, r12
    mov     [rbp - 48], rcx

.butterfly:
    mov     rcx, r11
    add     rcx, r12
    movsx   r8d, word [rbx + r11 * 2]           ; t      = r[j]
    movsx   r9d, word [rbx + rcx * 2]           ; u      = r[j + len]

    mov     eax, r8d
    add     eax, r9d
    BARRETT_REDUCE
    mov     [rbx + r11 * 2], ax                 ; r[j] = barrett(t + u)

    mov     eax, r9d
    sub     eax, r8d
    imul    eax, r10d
    MONT_REDUCE
    mov     rcx, r11
    add     rcx, r12
    mov     [rbx + rcx * 2], ax                 ; r[j+len] = zeta * (u - t)

    inc     r11
    cmp     r11, [rbp - 48]
    jb      .butterfly

    lea     r13, [r13 + r12 * 2]
    cmp     r13, 256
    jb      .block

    shl     r12, 1
    cmp     r12, 128
    jbe     .layer

    xor     rcx, rcx
.scale:
    movsx   eax, word [rbx + rcx * 2]
    imul    eax, MLKEM_INVNTT_F
    MONT_REDUCE
    mov     [rbx + rcx * 2], ax
    inc     rcx
    cmp     rcx, 256
    jb      .scale

    mov     rbx, [rbp - 8]
    mov     r12, [rbp - 16]
    mov     r13, [rbp - 24]
    mov     r14, [rbp - 32]
    mov     r15, [rbp - 40]
    FRAME_END
    ret

; -----------------------------------------------------------------------------
;  BASEMUL_PAIR <byte offset within the quadruple>, <zeta in a local>
;
;      r0 = a0*b0 + zeta * a1*b1
;      r1 = a0*b1 + a1*b0
;
;  rbx = r, r12 = a, r13 = b, r15 = the quadruple index, [rbp - 56] scratch.
;  A macro rather than a call: the two pairs of a quadruple differ only in the
;  sign of zeta, and two copies of this text would be two chances to write it
;  differently.
; -----------------------------------------------------------------------------
%macro BASEMUL_PAIR 2
    movsx   r8d,  word [r12 + r15 * 8 + %1]     ; a0
    movsx   r9d,  word [r12 + r15 * 8 + %1 + 2] ; a1
    movsx   r10d, word [r13 + r15 * 8 + %1]     ; b0
    movsx   r11d, word [r13 + r15 * 8 + %1 + 2] ; b1

    FQMUL   ecx, r9d, r11d                      ; a1 * b1
    FQMUL   ecx, ecx, dword %2                  ; * zeta
    mov     [rbp - 56], ecx
    FQMUL   ecx, r8d, r10d                      ; a0 * b0
    add     ecx, [rbp - 56]
    mov     [rbx + r15 * 8 + %1], cx

    FQMUL   ecx, r8d, r11d                      ; a0 * b1
    mov     [rbp - 56], ecx
    FQMUL   ecx, r9d, r10d                      ; a1 * b0
    add     ecx, [rbp - 56]
    mov     [rbx + r15 * 8 + %1 + 2], cx
%endmacro

; =============================================================================
;  cyboudb_mlkem_basemul(r, a, b)
;
;  Multiplication in the NTT domain is 128 products in F_q[X]/(X^2 - zeta) and
;  not 256 independent ones: the transform stops at degree-one remainders,
;  because q = 3329 has 256th roots of unity and no 512th ones. Getting this
;  wrong gives a KEM that decapsulates its own ciphertexts and nobody else's,
;  which is why the test multiplies polynomials the long way and compares.
; =============================================================================
cyboudb_mlkem_basemul:
    FRAME_BEGIN 80, 0
    mov     [rbp - 8], rbx
    mov     [rbp - 16], r12
    mov     [rbp - 24], r13
    mov     [rbp - 32], r14
    mov     [rbp - 40], r15

    mov     rbx, ARG1
    mov     r12, ARG2
    mov     r13, ARG3
    lea     r14, [mlkem_zetas]
    xor     r15, r15

.quad:
    mov     rax, r15
    add     rax, 64
    movsx   ecx, word [r14 + rax * 2]
    mov     [rbp - 64], ecx                     ; +zeta
    neg     ecx
    mov     [rbp - 72], ecx                     ; -zeta, for the second pair

    BASEMUL_PAIR 0, [rbp - 64]
    BASEMUL_PAIR 4, [rbp - 72]

    inc     r15
    cmp     r15, 64
    jb      .quad

    mov     rbx, [rbp - 8]
    mov     r12, [rbp - 16]
    mov     r13, [rbp - 24]
    mov     r14, [rbp - 32]
    mov     r15, [rbp - 40]
    FRAME_END
    ret

; =============================================================================
;  cyboudb_mlkem_poly_add(r, a, b)
;  cyboudb_mlkem_poly_sub(r, a, b)
;
;  Coefficient-wise, without reduction: the callers know how much growth they
;  can afford and reduce when they have to, which is what keeps the reductions
;  countable rather than sprinkled.
; =============================================================================
cyboudb_mlkem_poly_add:
    mov     r10, ARG1
    mov     r11, ARG2
    mov     r8, ARG3
    xor     rcx, rcx
.next:
    mov     ax, [r11 + rcx * 2]
    add     ax, [r8 + rcx * 2]
    mov     [r10 + rcx * 2], ax
    inc     rcx
    cmp     rcx, 256
    jb      .next
    ret

cyboudb_mlkem_poly_sub:
    mov     r10, ARG1
    mov     r11, ARG2
    mov     r8, ARG3
    xor     rcx, rcx
.next:
    mov     ax, [r11 + rcx * 2]
    sub     ax, [r8 + rcx * 2]
    mov     [r10 + rcx * 2], ax
    inc     rcx
    cmp     rcx, 256
    jb      .next
    ret

; =============================================================================
;  cyboudb_mlkem_poly_reduce(r)     - every coefficient into (-q/2, q/2]
;  cyboudb_mlkem_poly_tomont(r)     - every coefficient into the Montgomery
;                                     domain, which is a multiply by 2^32 mod q
; =============================================================================
cyboudb_mlkem_poly_reduce:
    mov     r10, ARG1
    xor     rcx, rcx
.next:
    mov     ax, [r10 + rcx * 2]
    BARRETT_REDUCE
    mov     [r10 + rcx * 2], ax
    inc     rcx
    cmp     rcx, 256
    jb      .next
    ret

cyboudb_mlkem_poly_tomont:
    mov     r10, ARG1
    xor     rcx, rcx
    mov     r11d, (1 << 32) % MLKEM_Q
.next:
    movsx   eax, word [r10 + rcx * 2]
    imul    eax, r11d
    MONT_REDUCE
    mov     [r10 + rcx * 2], ax
    inc     rcx
    cmp     rcx, 256
    jb      .next
    ret

%ifdef CybouDB_LINUX
section .note.GNU-stack noalloc noexec nowrite progbits
%endif
