#!/usr/bin/env python3
# Copyright (c) 2026 Stanislav Saveliev and CybouDB Contributors
# SPDX-License-Identifier: Apache-2.0
"""Generate tests/mlkem_fixture.h from OpenSSL 3.5's ML-KEM-768.

Everything else in this repository can be checked against a definition written
out a second way. ML-KEM cannot: writing it twice would be writing the same
misunderstanding twice, and the mistakes that matter here - a transposed
matrix, two index bytes in the wrong order, a hash fed its inputs backwards -
all produce something that works perfectly with itself.

OpenSSL 3.5 implements ML-KEM-768 and will print the 64-byte (d, z) seed of a
key it generated, so the strongest possible check is available for free: from
their seed, our key generation must produce their encapsulation key and their
decapsulation key, byte for byte. That pins every internal step - the matrix
sampling, the noise, the NTT, every encoding - not just the composition that
survives them.

This runs under WSL or Linux, needs OpenSSL 3.5 or newer, and writes the
header to stdout:

    python3 tools/gen_mlkem_fixture.py > tests/mlkem_fixture.h

The header is checked in, so the test suite does not need OpenSSL to run. What
needs OpenSSL is regenerating it, and the point of checking in the generator
beside the fixture is that the fixture is not a magic file.
"""
import re
import subprocess
import sys
import tempfile
import os

EK_BYTES = 1184
DK_BYTES = 2400
CT_BYTES = 1088
SS_BYTES = 32


def openssl(*args, **kw):
    return subprocess.run(('openssl',) + args, check=True,
                          capture_output=True, **kw).stdout


def parse_labelled_hex(text, label):
    """Pull one colon-separated hex block out of `openssl pkey -text`."""
    lines = text.splitlines()
    out = []
    collecting = False
    for line in lines:
        if line.startswith(label + ':'):
            collecting = True
            continue
        if collecting:
            if not line.startswith(' '):
                break
            stripped = line.strip()
            if not re.fullmatch(r'([0-9a-f]{2}:?)+', stripped):
                break
            out.extend(int(b, 16) for b in stripped.strip(':').split(':'))
    if not out:
        raise SystemExit('no %s in the key dump' % label)
    return bytes(out)


def c_array(name, data):
    rows = []
    for i in range(0, len(data), 12):
        rows.append('    ' + ' '.join('0x%02x,' % b for b in data[i:i + 12]))
    return ('static const uint8_t %s[%d] = {\n%s\n};\n'
            % (name, len(data), '\n'.join(rows)))


def main():
    version = openssl('version').decode()
    if 'OpenSSL 3.5' not in version and 'OpenSSL 3.6' not in version \
            and 'OpenSSL 4' not in version:
        sys.stderr.write('warning: expected OpenSSL 3.5 or newer, got %s'
                         % version)

    tmp = tempfile.mkdtemp()
    dk_pem = os.path.join(tmp, 'dk.pem')
    ek_pem = os.path.join(tmp, 'ek.pem')
    ct_bin = os.path.join(tmp, 'ct.bin')
    ss_bin = os.path.join(tmp, 'ss.bin')

    openssl('genpkey', '-algorithm', 'ML-KEM-768', '-out', dk_pem)
    openssl('pkey', '-in', dk_pem, '-pubout', '-out', ek_pem)

    priv_text = openssl('pkey', '-in', dk_pem, '-text', '-noout').decode()
    seed = parse_labelled_hex(priv_text, 'seed')
    dk = parse_labelled_hex(priv_text, 'dk')
    ek = parse_labelled_hex(priv_text, 'ek')

    if len(seed) != 64:
        raise SystemExit('seed is %d bytes, expected 64' % len(seed))
    if len(dk) != DK_BYTES or len(ek) != EK_BYTES:
        raise SystemExit('dk %d ek %d - not ML-KEM-768' % (len(dk), len(ek)))

    openssl('pkeyutl', '-encap', '-inkey', ek_pem, '-pubin',
            '-secret', ss_bin, '-out', ct_bin)
    with open(ct_bin, 'rb') as f:
        ct = f.read()
    with open(ss_bin, 'rb') as f:
        ss = f.read()
    if len(ct) != CT_BYTES or len(ss) != SS_BYTES:
        raise SystemExit('ciphertext %d secret %d' % (len(ct), len(ss)))

    out = sys.stdout
    out.write('/* Generated by tools/gen_mlkem_fixture.py - do not edit.\n'
              ' *\n'
              ' * An ML-KEM-768 key pair from %s, with the 64-byte seed it\n'
              ' * was generated from, and one ciphertext under it.\n'
              ' *\n'
              ' * The seed is what makes this a real check rather than a\n'
              ' * regression lock: our key generation is run on their seed and\n'
              ' * must produce their bytes.\n'
              ' *\n'
              ' * SPDX-License-Identifier: Apache-2.0\n'
              ' */\n' % version.strip())
    out.write('\n/* d and z are the two halves of the seed. */\n')
    out.write(c_array('fixture_d', seed[:32]))
    out.write(c_array('fixture_z', seed[32:]))
    out.write('\n')
    out.write(c_array('fixture_ek', ek))
    out.write('\n')
    out.write(c_array('fixture_dk', dk))
    out.write('\n/* Their encapsulation, and the secret it carries. */\n')
    out.write(c_array('fixture_ct', ct))
    out.write(c_array('fixture_ss', ss))


if __name__ == '__main__':
    main()
