#!/usr/bin/env python3
# Copyright (c) 2026 Stanislav Saveliev and CybouDB Contributors
# SPDX-License-Identifier: Apache-2.0
"""Generate tests/kmac_fixture.h from OpenSSL's KMAC256.

The point of moving the seal tree and the key hierarchy onto KMAC is that a
standard construction can be checked against somebody else's implementation.
This is that somebody else: OpenSSL 3 implements KMAC256 with a key, a
customization string and an output length, which is the whole of the interface
CybouDB uses.

The cases below are chosen to exercise what the encodings actually do - a
customization string that is empty and one that is not, a message shorter than
a rate and one longer than two, an output length under 256 bits and one over,
and a key at the 64-byte cap.

    python3 tools/gen_kmac_fixture.py > tests/kmac_fixture.h
"""
import subprocess
import sys


def kmac256(key, msg, out_len, custom):
    args = ['openssl', 'mac', '-macopt', 'hexkey:' + key.hex(),
            '-macopt', 'size:%d' % out_len]
    if custom:
        args += ['-macopt', 'custom:' + custom.decode('ascii')]
    args.append('KMAC256')
    out = subprocess.run(args, input=msg, capture_output=True, check=True)
    return bytes.fromhex(out.stdout.decode().strip())


def c_array(name, data):
    if not data:
        return 'static const uint8_t %s[1] = { 0 };\n' % name
    rows = []
    for i in range(0, len(data), 12):
        rows.append('    ' + ' '.join('0x%02x,' % b for b in data[i:i + 12]))
    return ('static const uint8_t %s[%d] = {\n%s\n};\n'
            % (name, len(data), '\n'.join(rows)))


CASES = [
    # (label, key, message, output bytes, customization)
    ('short',   bytes(range(0x40, 0x60)), bytes([0, 1, 2, 3]), 32, b''),
    ('custom',  bytes(range(0x40, 0x60)), bytes([0, 1, 2, 3]), 64,
     b'My Tagged Application'),
    ('long',    bytes(range(0x40, 0x60)), bytes(range(200)), 32,
     b'CybouDB/0.7/seal-leaf'),
    ('tag128',  bytes(range(0x40, 0x60)), bytes(range(136)), 16,
     b'CybouDB/0.7/seal-node'),
    ('maxkey',  bytes(range(64)),          bytes([0xAA] * 4000), 32,
     b'CybouDB/0.7/kdf'),
    ('emptymsg', bytes(range(0x40, 0x60)), b'', 32, b'x'),
]


def main():
    version = subprocess.run(['openssl', 'version'], capture_output=True,
                             check=True).stdout.decode().strip()
    out = sys.stdout
    out.write('/* Generated by tools/gen_kmac_fixture.py - do not edit.\n'
              ' *\n'
              ' * KMAC256 from %s. The cases exercise the encodings: an empty\n'
              ' * customization string and a real one, a message shorter than\n'
              ' * one rate and one longer than two, an output under 256 bits\n'
              ' * and one over, and a key at the 64-byte cap.\n'
              ' *\n'
              ' * SPDX-License-Identifier: Apache-2.0\n'
              ' */\n\n' % version)

    out.write('typedef struct {\n'
              '    const char *name;\n'
              '    const uint8_t *key;    uint64_t key_len;\n'
              '    const uint8_t *msg;    uint64_t msg_len;\n'
              '    const uint8_t *custom; uint64_t custom_len;\n'
              '    const uint8_t *want;   uint64_t want_len;\n'
              '} kmac_case;\n\n')

    for label, key, msg, out_len, custom in CASES:
        tag = kmac256(key, msg, out_len, custom)
        out.write(c_array('kmac_%s_key' % label, key))
        out.write(c_array('kmac_%s_msg' % label, msg))
        out.write(c_array('kmac_%s_custom' % label, custom))
        out.write(c_array('kmac_%s_want' % label, tag))
        out.write('\n')

    out.write('static const kmac_case kmac_cases[] = {\n')
    for label, key, msg, out_len, custom in CASES:
        out.write('    { "%s", kmac_%s_key, %d, kmac_%s_msg, %d, '
                  'kmac_%s_custom, %d, kmac_%s_want, %d },\n'
                  % (label, label, len(key), label, len(msg), label,
                     len(custom), label, out_len))
    out.write('};\n')


if __name__ == '__main__':
    main()
