#!/usr/bin/env python3
# Copyright (c) 2026 Stanislav Saveliev and CybouDB Contributors
# SPDX-License-Identifier: Apache-2.0
"""Generate the NTT constants for ML-KEM, from their definitions.

The Keccak rho/pi moves were generated rather than transcribed for a reason
that applies twice over here: a single wrong entry in a table of 128 twiddle
factors produces code that still looks like an NTT, still runs, and still
returns something. It simply returns the wrong polynomial, and the only thing
that notices is a test with an independent implementation behind it.

So the table is derived here from what it is defined to be - 17 is a primitive
256th root of unity modulo 3329, the i-th twiddle is 17 raised to the
bit-reversal of i, in the Montgomery domain - and written into an include the
assembly uses verbatim.

    python3 tools/gen_mlkem_tables.py > src/crypto/mlkem_zetas.inc
"""
import sys

Q = 3329
N = 256
ROOT = 17
MONT = pow(2, 16, Q)            # 2^16 mod q
QINV = pow(Q, -1, 1 << 16)      # q^-1 mod 2^16, what Montgomery reduction needs


# Compression divides by q on data that is secret, so the assembly does it as
# a multiply and a shift. These are the constants - and the check below is
# what makes them a fact rather than a hope: the identity is verified against
# the real division for every value compression can present, not for a sample
# of them.
DIV_SHIFT = 33
DIV_MAGIC = ((1 << DIV_SHIFT) + Q - 1) // Q
DIV_LIMIT = (Q << 10) + Q       # the largest n that ten-bit compression forms


def check_division_constant():
    for n in range(DIV_LIMIT):
        if (n * DIV_MAGIC >> DIV_SHIFT) != n // Q:
            raise SystemExit('division constant wrong at n = %d' % n)


def brv7(i):
    """Bit-reversal of a 7-bit index, which is the order the NTT visits."""
    return int(format(i, '07b')[::-1], 2)


def signed(x):
    """Centred representative: the assembly holds coefficients as int16."""
    return x - Q if x > Q // 2 else x


def rows(values, per_row=8):
    for i in range(0, len(values), per_row):
        yield '    dw ' + ', '.join('%6d' % v for v in values[i:i + per_row])


def main():
    check_division_constant()
    assert pow(ROOT, 128, Q) == Q - 1, 'not a primitive 256th root'
    assert pow(ROOT, N, Q) == 1
    assert (Q * QINV) % (1 << 16) == 1

    zetas = [signed(pow(ROOT, brv7(i), Q) * MONT % Q) for i in range(128)]

    out = sys.stdout
    out.write('; Generated by tools/gen_mlkem_tables.py - do not edit.\n')
    out.write('; FIPS 203: q = %d, n = %d, a primitive 256th root of unity\n'
              '; is %d, and these are its powers in bit-reversed order, in\n'
              '; the Montgomery domain (multiplied by 2^16 mod q).\n'
              % (Q, N, ROOT))
    out.write(';\n; The first eight are -1044, -758, -359, -1517, 1493, 1422,\n'
              '; 287, 202 - the values every published Kyber implementation\n'
              '; begins with, which is the cheapest possible check that this\n'
              '; generator agrees with the rest of the world.\n\n')
    out.write('%%define MLKEM_Q     %d\n' % Q)
    out.write('%%define MLKEM_QINV  %d          ; q^-1 mod 2^16\n' % QINV)
    out.write('%%define MLKEM_MONT  %d           ; 2^16 mod q\n\n' % MONT)
    out.write('; Verified exhaustively by this generator: n / q equals\n'
              '; (n * %d) >> %d for every n up to %d, which is the largest\n'
              '; value ten-bit compression can form.\n'
              % (DIV_MAGIC, DIV_SHIFT, DIV_LIMIT))
    out.write('%%define MLKEM_DIV_M %d\n' % DIV_MAGIC)
    out.write('%%define MLKEM_DIV_S %d\n\n' % DIV_SHIFT)
    out.write('align 32\nmlkem_zetas:\n')
    for row in rows(zetas):
        out.write(row + '\n')
    out.write('\n')


if __name__ == '__main__':
    main()
